c_compiler:
  - gcc                        # [linux and aarch64]
  - clang                      # [osx]
  - vs2017                     # [win]
c_compiler_version:        # [linux or osx]
  - 11.2.0                 # [linux]
  - 14                     # [osx]
cxx_compiler:
  - gxx                        # [linux and aarch64]
  - clangxx                    # [osx]
  - vs2017                     # [win]
cxx_compiler_version:      # [linux or osx]
  - 11.2.0                 # [linux]
  - 14                     # [osx]
