{% set name = "librsvg" %}
{% set version = "2.54.3" %}
{% set abi_version = "2.0" %}
{% set version_majmin = version.rsplit('.', 1)[0] %}
{% set sha256 = "66158f2ef46dde260026846c4da102e4a9dd4e5293010f30949c6cc26dd6efe8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - patches/0001_add_rust_lto.patch
    - patches/0003_fix_win_when_doc_not_built # see https://gitlab.gnome.org/GNOME/librsvg/-/merge_requests/703

build:
  number: 0
  run_exports:
    # Looks good but no new info after 2.43 so keeping it x.x for safety.
    # https://abi-laboratory.pro/?view=timeline&l=librsvg
    - {{ pin_subpackage('librsvg', max_pin='x') }}
  missing_dso_whitelist:         # [linux and (x86_64 or s390x)]
    - '**/libc.so.6'             # [linux and x86_64]
    - '**/libpthread.so.0'       # [linux and x86_64]
    - '**/libdl.so.2'            # [linux and x86_64]
    - '**/librt.so.1'            # [linux and x86_64]
    - '**/libm.so.6'             # [linux and x86_64]
    - '**/ld-linux-x86-64.so.2'  # [linux and x86_64]
    - '**/ld64.so.1'             # [linux and s390x]
  ignore_run_exports:
    - pixman

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - gobject-introspection
    - pkg-config
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - autoconf    # [unix]
    - automake    # [unix]
    - libtool     # [unix]
    - patch       # [unix]
    - m2-patch    # [win]
    - gnuconfig   # [unix]
    - pthread-stubs                      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('xorg-x11-util-macros') }}  # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libx11-common') }}         # [linux]
    - {{ cdt('libx11') }}                # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
  host:
    - gobject-introspection
    - glib >=2.50.0
    - gettext   # [osx]
    - harfbuzz >=2.0.0
    - fontconfig  # [not win]
    - libiconv  # [win and osx]
    - libxml2 >=2.9.0
    - cairo >=1.16.0
    - gdk-pixbuf >=2.20
    - pango >=1.48.11
    - libpng
    - libzip
    - freetype
  run:
    - harfbuzz >=2.0.0
    - fontconfig  # [not win]
    - libiconv  # [win or osx]
    - libxml2 >=2.9.0
    - cairo >=1.16.0
    - gdk-pixbuf >=2.20
    - pango >=1.48.11
    - libpng
    - zlib
    - freetype

test:
  requires:
    - pkg-config
  commands:
    - rsvg-convert --version

    {% set name_abi = name + "-" + abi_version %}
    {% set lib = name + "-" + abi_version.split('.', 1)[0] %}  # [unix]
    {% set lib = "rsvg-" + abi_version %}  # [win]
    {% set vs_major = dict(vs2015="14", vs2017="15", vs2019="16")[c_compiler] %}  # [win]

    # verify that libs get installed and can be located through pkg-config
    - test -f $PREFIX/lib/{{ lib }}${SHLIB_EXT}  # [unix]
    - test ! -f $PREFIX/lib/{{ lib }}.a  # [unix]
    - test -f `pkg-config --variable=libdir --dont-define-prefix {{ name_abi }}`/{{ lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\{{ lib }}-vs{{ vs_major }}.dll exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=exec_prefix --dont-define-prefix {{ name_abi }}`) do if not exist "%%a/bin/{{ lib }}-vs{{ vs_major }}.dll" exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ lib }}.lib exit 1  # [win]
    - for /f "usebackq tokens=*" %%a in (`pkg-config --variable=libdir --dont-define-prefix {{ name_abi }}`) do if not exist "%%a/{{ lib }}.lib" exit 1  # [win]

    # verify that gdk-pixbuf loader library gets installed
    - test -f $PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so  # [unix]
    - test ! -f $PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.a  # [unix]
    - if not exist %PREFIX%\\Library\\lib\\gdk-pixbuf-2.0\\2.10.0\\loaders\\libpixbufloader-svg.dll exit 1  # [win]

    # verify that headers get installed
    - test -f $PREFIX/include/{{ name_abi }}/{{ name }}/rsvg-features.h  # [unix]
    - test -f $PREFIX/include/{{ name_abi }}/{{ name }}/rsvg-cairo.h  # [unix]
    - test -f $PREFIX/include/{{ name_abi }}/{{ name }}/rsvg.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\{{ name_abi }}\\{{ name }}\\rsvg-features.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\{{ name_abi }}\\{{ name }}\\rsvg-cairo.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\{{ name_abi }}\\{{ name }}\\rsvg.h exit 1  # [win]

    # test for gobject-introspection files
    - test -f $PREFIX/lib/girepository-1.0/Rsvg-2.0.typelib  # [unix]
    - if not exist %LIBRARY_LIB%\\girepository-1.0\\Rsvg-2.0.typelib exit 1  # [win]

about:
  home: https://wiki.gnome.org/Projects/LibRsvg
  license: LGPL-2.1-or-later
  license_file: COPYING.LIB
  license_family: LGPL
  summary: librsvg is a library to render SVG files using cairo.
  dev_url: https://gitlab.gnome.org/GNOME/librsvg
  doc_url: https://gnome.pages.gitlab.gnome.org/librsvg/doc/librsvg/index.html
  doc_source_url: https://gitlab.gnome.org/GNOME/librsvg/-/tree/main/doc

extra:
  recipe-maintainers:
    - pkgw
    - tschoonj
