travis:
  secure:
    BINSTAR_TOKEN: DbRh6DB3genZCFLMa90gdq6gGWsjyCbrDDnUvxHCLecq2wnx9jLIJwTMMVEoFFLuUfmjgekypjtSfRuDAbWd+V6sB2u2Zh0bUqcdmRfimTYbYJqdBMJKshHu1xRSgEtkmXMNAF/52bXZoeEOpYeqLYWsNWbIMkrXQUS1AC/A3GaoIiN95f6mYWJFDtSdLR6dplAsvIwie9FkFDfU/Wy5LFXdlgr69JzUTYzg+A1sFWSPCScEgJO53kLNhKbD3U2TcfxhtbEzTafpHxgmLC5UMgArcr1F8vjzc0gQ6G+tYRs5SdnSiuKfrCbp8/3z9sY8Eiz4XDs4x79Z3Onpml5KZsTux8IY9jmU1vxU1cC4vBYYev/XhBRl+K6krV+1yBnhBbCSALmAsmIZ8molXe8uu92xESimC8I/iRdhNTbIt1Z+1zs8r4uLB5DzN9T72J+F4tgV6gs6uB5UP08B4CetWlxzYZNiP7aUh81wiuGP3zNI/VztVKGAHNZnO9dvrC3vmZ74UUxeyMUZX47f+jD98xcRUBRr4xV4Q3nf9GtNjeyiEsLoLtkJBU2zEUURD4EiUfh+aJazRF/unORTDUel3HaSxEDlOE4HLyvadMgU2dI/X9lrwGgaaMGhrGUIWOrGDZbcl/yWgTuNszBIech0Bu4ToqIRyum5iQ/QdS0/mgE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
