travis:
  secure:
    BINSTAR_TOKEN: Gt8lkSE+eXTHXox8RhTRtTogYd8BH64tdkivhCT9ELdwAYNkkg6n7IUrdRs/CnW/f4g0lOZ4uvMuPeKJ7om9QemcTuErt200Ej2GWW4AmSPgEacult+MIMr9pGCLP45Z9U6YX/UqwHsdGC1EoVQDAG0Jyc0jQ4oV5ZKHgXNQVRQ/0NGQpsJT7fy798I2j4dCbgE4ZrQ0ETasxgmhWY2C6VScVliTqf7yB/EZVf6E66VTQpnUOj3DRN6NTPdFnHNy+MMdZEioAiqeuZVtFjDSh3soM/hFKKwTdQbk2rin7hvhpTYGM+k0rgg4tBo62TnizlUSZtWHv/20N0cM/AYZ+okPbnB4BHX3bpmU/q/eq34FKIh6dgwPZ2b3593EiHWfokKlShRqLbvdN2mODtYOTcRa9kh7QJh18pgiGErAer/KR2nZQRAOXURbM63UOz0G4DOLX7BlZBNPrptrNmSoLrZjlMj2/TJDSh0cVNWhV1hGFNVo5fe1Vh6caWltrclPfr/59Tw9QfgRcBVlwzyUyDL2BUDPCc34va9FKpWSwBEcf5pVfeD/ie89HFZmAR0liHuBmotpLZLnHQTZAecDrYxxSw0aRKOqYwuy+EMQSeloSFdfHsKmTpfS/HgdUum2SDPw7Zd7zu/gUTdRgV/Y/wUjfmQzlmML4PteoK9Ei9w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
